# Generated by Django 5.0.8 on 2024-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
                ('status_key', models.CharField(blank=True, max_length=30, null=True)),
                ('external_url', models.URLField()),
                ('description', models.TextField()),
                ('routing_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
