# Generated by Django 5.0.8 on 2024-08-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='status_key',
            new_name='data_key',
        ),
    ]
