# Generated by Django 5.0.8 on 2024-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_status_key_devices_data_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
