# Generated by Django 5.0.8 on 2024-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_devices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='external_url',
            field=models.CharField(max_length=200),
        ),
    ]
