# Generated by Django 5.0.8 on 2024-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_devices_data_key_remove_devices_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='id',
        ),
        migrations.AlterField(
            model_name='devices',
            name='Device_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
