# Generated by Django 5.0.8 on 2024-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_devices_id_alter_devices_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(blank=True, choices=[('Slider', 'Slider'), ('Toggle Button', 'Toggle Button'), ('Push Button', 'Push Button'), ('Series', 'Series')], max_length=50, null=True),
        ),
    ]
