# Generated by Django 5.1.1 on 2025-01-24 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7b14e451-21e4-5412-8d9a-395f0b3a7e52'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7b14e451-21e4-5412-8d9a-395f0b3a7e52'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('element_id', models.CharField(max_length=50, unique=True)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementPermissionsGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.CharField(choices=[('R', 'Read'), ('RC', 'Read and change')], max_length=2)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_red.element')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'element'), name='unique_group_element')],
            },
        ),
        migrations.CreateModel(
            name='ElementPermissionsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.CharField(choices=[('R', 'Read'), ('RC', 'Read and change')], max_length=2)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_red.element')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'element'), name='unique_user_element')],
            },
        ),
    ]
