# Generated by Django 5.1.5 on 2025-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
