# Generated by Django 5.1.5 on 2025-01-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0002_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_red.device'),
            preserve_default=False,
        ),
    ]
