# Generated by Django 5.1.5 on 2025-01-24 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0003_element_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21fc3438-7989-5665-9722-e3808d094545'), editable=False, primary_key=True, serialize=False),
        ),
    ]
