# Generated by Django 5.1.5 on 2025-01-29 03:53

import django.db.models.deletion
import node_red.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0005_alter_device_id_alter_element_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.UUIDField(default=node_red.models.generate_uuid_connection, editable=False, primary_key=True, serialize=False)),
                ('detail', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='node_red.device')),
            ],
        ),
    ]
