# Generated by Django 5.1.5 on 2025-01-29 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0006_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
