# Generated by Django 5.1.5 on 2025-01-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0007_connections_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='detail',
        ),
        migrations.AddField(
            model_name='connections',
            name='details',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
