# Generated by Django 5.1.5 on 2025-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0008_remove_connections_detail_connections_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
