# Generated by Django 5.1.5 on 2025-02-01 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0009_element_details_alter_element_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
